export enum ResponseCode {
  SUCCESS = "000",
  NOT_FOUND = "A04",
  SERVER_ERROR = "A05",
  BAD_REQUEST = "A06",
  UNAUTHORIZED = "A07",
  FORBIDDEN = "A08",
  CONFLICT = "A09",
  VALIDATION_ERROR = "A10",
  RATE_LIMIT_EXCEEDED = "A11",
  SERVICE_UNAVAILABLE = "A12",
}
